name: hidable_animate
description: Widget, that can make any static located widget hidable and animate (scroll to hide)
version: 0.0.1
homepage: https://github.com/ipilot7/hidable_animate

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
